Card Create
GGabrielDev/Henry-PF pull request #12
Opened 2022-10-26 19:18 UTC by JuanGaretto

2022-10-27 11:28 UTC, GGabrielDev requested changes
Revisar los comentarios y realizar cambios pertinentes.

Tambien hacer un `git pull` para tratar el error de merge que se presenta en el Pull Request

2022-10-27 11:28 UTC, GGabrielDev commented on client/src/components/Card.tsx
> +import { Themes } from "./Theme/Theme";
Utilizar ThemeProvider de styled-components. (Borrar este import y utilizar las props dentro de los styled components en su lugar. En un comentario posterior se explica como.)

2022-10-27 11:28 UTC, GGabrielDev commented on client/src/components/Card.tsx
> +const CardContainer = styled.div`
Dividir un poco mas los componentes de styled-components. Se que este metodo de estilizado es valido tambien, pero tener todos los componentes hijos como classNames en lugar de sus respectivos componentes quita un poco el proposito. Tenerlos separados en mas componentes mejora la lectura del JSX.

2022-10-27 11:28 UTC, GGabrielDev commented on client/src/components/Card.tsx
> +    border:2px solid ${Themes.primary};
Remplazar para usar el ThemeProvider de styled-components en su lugar.
```suggestion
    border:2px solid ${({theme}) => theme.primary};
```

2022-10-29 10:52 UTC, GGabrielDev requested changes
Pasar el uso de colores al theme de styled components

2022-10-29 10:52 UTC, GGabrielDev commented on client/src/Pages/Detalle.tsx
> +  background-color: blue;
Usar los colores de los theme en lugar de colores estaticos. Ejemplo: `background-color: ${({theme}) => theme.primary}`

2022-10-29 10:52 UTC, GGabrielDev commented on client/src/components/Home/Filtros/Filtros.tsx
> +import { Themes } from "../../Theme/Theme";
No importar Theme directamente dentro de los archivos. Utilizad la propiedad `theme` de styled-components en su lugar.

2022-10-30 04:51 UTC, JuanGaretto commented on client/src/Pages/Detalle.tsx
> +  background-color: blue;
eso no estaba terminado, solamente lo uso como referencia para ubicarlo dentro de la pagina

2022-10-30 17:27 UTC, merged